baseURL: "https://muramoto-h.github.io/" 
title: Hugo Muramoto
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1 
        - name: Teaching
          url: teaching/
          weight: 2
        - name: CV
          url: CV_HugoMuramoto.pdf
          weight: 3
        
params:
    description: "I'm a MSc student in Economics at Sao Paulo School of Economics, Brazil. I'm particularly interested in Macroeconomics, Forecasting and International Trade."
    author: Hugo Muramoto
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hugo Muramoto
          subtitle: "Greetings! <br><br> I'm a **MSc student in Economics** at [Sao Paulo School of Economics](https://economics-sp.fgv.br/), Brazil. <br><br> I'm particularly interested in Macroeconomics, Forecasting and International Trade. <br><br> When I'm not in economist and researcher mode, you can usually find me out for a walk in the park, trying out new food spots, or watching anime, series and movies. I also enjoy studying languages, or sometimes just having a quiet day at home."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/ 
            - name: Teaching
              url: teaching/
            - name: CV
              url: CV_HugoMuramoto.pdf

    socialIcons:
        - name: CV
          url: CV_HugoMuramoto.pdf
        - name: Email
          url: mailto:hugo.muramoto@fgv.edu.br
        - name: LinkedIn
          url: https://www.linkedin.com/in/hugo-muramoto/
        - name: Instagram
          url: https://www.instagram.com/hugo_muramoto
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hugo Muramoto"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
